"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");
const vm = require("node:vm");

function loadSchematicApi(options = {}) {
  const window = {
    addEventListener() {},
    AliceOledDevice: require("../oled-device.js"),
    AliceSpiDisplayDevice: require("../spi-display-device.js"),
    AliceLightSensorDevice: require("../light-sensor-device.js"),
    AlicePeripheralCatalog: require("../peripheral-catalog.js"),
    AlicePeripheralDevices: require("../peripheral-devices.js"),
    AliceHalSimulator: options.halSimulator || null
  };
  const document = {
    readyState: "loading",
    addEventListener() {},
    body: null
  };
  const context = vm.createContext({
    window,
    document,
    Blob,
    CustomEvent: function CustomEvent(type, options) {
      this.type = type;
      this.detail = options && options.detail;
    },
    console,
    queueMicrotask,
    setTimeout,
    clearTimeout
  });
  const source = fs.readFileSync(path.join(__dirname, "..", "schematic.js"), "utf8");
  vm.runInContext(source, context, { filename: "schematic.js" });
  return window.AliceSchematic;
}

function sampleCircuit() {
  return {
    schemaVersion: 1,
    kind: "AliceSIMCircuit",
    mcu: "UNTRUSTED-MCU-NAME",
    components: [
      {
        id: "component-20",
        type: "mcu",
        ref: "U7",
        value: "UNTRUSTED-MCU-VALUE",
        x: 80,
        y: 100,
        rotation: 0,
        autoGenerated: true,
        autoSource: "system",
        autoKey: "mcu"
      },
      {
        id: "component-21",
        type: "vcc",
        ref: "PWR9",
        value: "+3V3",
        x: 130,
        y: 20,
        rotation: 0
      },
      {
        id: "component-30",
        type: "oled",
        ref: "OLED4",
        value: "SSD1306 - 0x3D",
        x: 280,
        y: 40,
        rotation: 90,
        oledAddress: "0x3D"
      },
      {
        id: "component-40",
        type: "lightSensor",
        ref: "LS6",
        value: "25000 lux",
        x: 400,
        y: 250,
        rotation: 270,
        lux: 25000,
        thresholdLux: 18000,
        adcBits: 10,
        adcReferenceVoltage: 3.0,
        supplyVoltage: 5,
        minOperatingVoltage: 2.5,
        maxOperatingVoltage: 5.5,
        sensorGamma: 1.4,
        analogInverted: true,
        digitalActiveLow: true
      },
      {
        id: "component-55",
        type: "resistor",
        ref: "R12",
        value: "4.7 kOhm",
        x: 320,
        y: 100,
        rotation: 0
      }
    ],
    wires: [
      {
        id: "wire-31",
        from: { componentId: "component-20", pin: "PC13" },
        to: { componentId: "component-55", pin: "1" },
        signal: "PC13",
        route: [
          { x: 250, y: 130 },
          { x: 270, y: 130 },
          { x: 270, y: 126 },
          { x: 320, y: 126 }
        ]
      },
      {
        id: "wire-32",
        from: { componentId: "component-20", pin: "PA0" },
        to: { componentId: "component-55", pin: "2" },
        signal: "PA0",
        route: [
          { x: 250, y: 150 },
          { x: 300, y: 150 },
          { x: 300, y: 126 },
          { x: 416, y: 126 }
        ]
      }
    ],
    view: { zoom: 1.35, panX: -42, panY: 18, userView: true }
  };
}

test("circuit import/export restores device properties, rotation, view and full routes", () => {
  const api = loadSchematicApi();
  const result = api.importCircuit(sampleCircuit());

  assert.equal(result.ok, true, JSON.stringify(result));
  assert.equal(result.wireCount, 1);
  assert.equal(result.skippedWireCount, 1);
  assert.equal(result.skippedWires[0].reason, "ioc-pin-unavailable");
  assert.match(result.warnings.join("\n"), /active IOC MCU remains STM32F103C8T6/);

  const saved = JSON.parse(JSON.stringify(api.exportCircuit()));
  assert.equal(saved.schemaVersion, 1);
  assert.equal(saved.kind, "AliceSIMCircuit");
  assert.equal(saved.mcu, "STM32F103C8T6");
  assert.deepEqual(saved.view, { zoom: 1.35, panX: -42, panY: 18, userView: true });

  const mcu = saved.components.find((component) => component.type === "mcu");
  assert.equal(mcu.value, "STM32F103C8T6");
  assert.equal(mcu.ref, "U7");

  const oled = saved.components.find((component) => component.type === "oled");
  assert.equal(oled.rotation, 90);
  assert.equal(oled.x, 280);
  assert.equal(oled.y, 40);
  assert.equal(oled.oledAddress, 0x3d);

  const sensor = saved.components.find((component) => component.type === "lightSensor");
  assert.equal(sensor.rotation, 270);
  assert.equal(sensor.lux, 25000);
  assert.equal(sensor.thresholdLux, 18000);
  assert.equal(sensor.adcBits, 10);
  assert.equal(sensor.adcReferenceVoltage, 3.0);
  assert.equal(sensor.supplyVoltage, 5);
  assert.equal(sensor.sensorGamma, 1.4);
  assert.equal(sensor.analogInverted, true);
  assert.equal(sensor.digitalActiveLow, true);

  assert.equal(saved.wires.length, 1);
  assert.deepEqual(saved.wires[0].route, [
    { x: 250, y: 130 },
    { x: 270, y: 130 },
    { x: 270, y: 126 },
    { x: 320, y: 126 }
  ]);
});

test("toggle switches persist their state and electrically connect both pins only when on", () => {
  const api = loadSchematicApi();
  api.setMcuConfiguration({
    mcu: "STM32F103C8T6",
    pins: [{ pin: "PA1", physicalPin: "PA1", mode: "GPIO_Input", signal: "GPIO_Input", label: "RUN_SWITCH" }]
  });
  const circuit = {
    schemaVersion: 1,
    kind: "AliceSIMCircuit",
    mcu: "STM32F103C8T6",
    components: [
      { id: "mcu", type: "mcu", ref: "U1", value: "STM32F103C8T6", x: 80, y: 100, rotation: 0 },
      { id: "ground", type: "ground", ref: "GND1", value: "0V", x: 400, y: 200, rotation: 0 },
      { id: "switch", type: "button", ref: "SW1", value: "OFF", buttonClosed: false, x: 260, y: 150, rotation: 0 }
    ],
    wires: [
      { id: "wire-1", from: { componentId: "mcu", pin: "PA1" }, to: { componentId: "switch", pin: "1" }, signal: "PA1", route: [{ x: 250, y: 150 }, { x: 260, y: 150 }] },
      { id: "wire-2", from: { componentId: "switch", pin: "2" }, to: { componentId: "ground", pin: "GND" }, signal: "GND", route: [{ x: 338, y: 180 }, { x: 432, y: 180 }, { x: 432, y: 200 }] }
    ],
    view: { zoom: 1, panX: 0, panY: 0, userView: true }
  };

  assert.equal(api.importCircuit(circuit).ok, true);
  assert.equal(api.sampleMcuPin("PA1"), null);
  assert.equal(api.setButtonClosed("switch", true), true);
  assert.equal(api.sampleMcuPin("PA1"), 0);
  const savedSwitch = api.exportCircuit().components.find(component => component.id === "switch");
  assert.equal(savedSwitch.buttonClosed, true);
  assert.equal(savedSwitch.value, "ON");
});

test("serializeCircuit accepts an exported payload and invalid imports are atomic", () => {
  const api = loadSchematicApi();
  assert.equal(api.importCircuit(JSON.stringify(sampleCircuit())).ok, true);
  const before = api.serializeCircuit();
  const payload = api.exportCircuit();
  const serializedPayload = api.serializeCircuit(payload, 0);
  assert.deepEqual(JSON.parse(serializedPayload), JSON.parse(before));

  const invalid = JSON.parse(before);
  invalid.wires[0].to.pin = "NOT_A_PIN";
  const failed = api.importCircuit(invalid);
  assert.equal(failed.ok, false);
  assert.equal(failed.code, "INVALID_COMPONENT_PIN");
  assert.equal(api.serializeCircuit(), before);
});

test("wire bend editing inserts, removes and persists orthogonal control points", () => {
  const api = loadSchematicApi();
  assert.equal(api.importCircuit(sampleCircuit()).ok, true);
  const before = api.getState().wires[0];
  const inserted = api.insertWireBend(before.id, 2, { x: 295, y: 126 });
  assert.ok(inserted);
  assert.ok(inserted.length > before.route.length);
  for (let index = 1; index < inserted.length; index += 1) {
    assert.ok(inserted[index - 1].x === inserted[index].x || inserted[index - 1].y === inserted[index].y);
  }

  const saved = api.exportCircuit();
  assert.deepEqual(saved.wires[0].route, inserted);
  const bendIndex = inserted.findIndex((point, index) => index > 0 && index < inserted.length - 1 &&
    inserted[index - 1].x !== inserted[index + 1].x && inserted[index - 1].y !== inserted[index + 1].y);
  assert.ok(bendIndex > 0);
  const removed = api.removeWireBend(before.id, bendIndex);
  assert.ok(removed);
  for (let index = 1; index < removed.length; index += 1) {
    assert.ok(removed[index - 1].x === removed[index].x || removed[index - 1].y === removed[index].y);
  }
});

test("loading a circuit preserves the active IOC MCU identity and pin layout", () => {
  const api = loadSchematicApi();
  assert.equal(api.importCircuit(sampleCircuit()).ok, true);
  api.setMcuConfiguration({
    mcu: "STM32F103C8T6",
    configuredPins: [
      { base: "PB6", signal: "I2C1_SCL", mode: "communication" },
      { base: "PB7", signal: "I2C1_SDA", mode: "communication" }
    ]
  });

  const replacement = {
    schemaVersion: 1,
    kind: "AliceSIMCircuit",
    mcu: "ATTEMPTED-MCU-OVERRIDE",
    components: [
      { id: "foreign-mcu", type: "mcu", ref: "U99", value: "ATTEMPTED-MCU-OVERRIDE", x: 100, y: 80, rotation: 0 },
      { id: "component-90", type: "oled", ref: "OLED9", value: "SSD1306 - 0x3C", x: 420, y: 120, rotation: 0, oledAddress: 0x3c }
    ],
    wires: [
      {
        id: "wire-90",
        from: { componentId: "foreign-mcu", pin: "PB6" },
        to: { componentId: "component-90", pin: "SCL" },
        signal: "I2C1_SCL",
        route: [{ x: 250, y: 120 }, { x: 552, y: 120 }, { x: 552, y: 148 }]
      }
    ],
    view: { zoom: 1, panX: 0, panY: 0 }
  };

  const result = api.importCircuit(replacement);
  assert.equal(result.ok, true);
  assert.equal(result.skippedWireCount, 0);
  const saved = JSON.parse(JSON.stringify(api.exportCircuit()));
  const mcus = saved.components.filter((component) => component.type === "mcu");
  assert.equal(mcus.length, 1);
  assert.equal(mcus[0].id, "component-20");
  assert.equal(mcus[0].value, "STM32F103C8T6");
  assert.equal(saved.wires[0].from.componentId, "component-20");
  assert.equal(saved.wires[0].from.pin, "PB6");
});

test("downloadCircuit returns a safe JSON fallback when downloads are unavailable", () => {
  const api = loadSchematicApi();
  assert.equal(api.importCircuit(sampleCircuit()).ok, true);
  const result = api.downloadCircuit("demo:circuit");
  assert.equal(result.ok, false);
  assert.equal(result.filename, "demo-circuit.alice-sch.json");
  assert.equal(JSON.parse(result.content).kind, "AliceSIMCircuit");
});

test("complete circuits export as independent reusable component packages", () => {
  const api = loadSchematicApi();
  const payload = sampleCircuit();
  payload.components.push(
    { id: "terminal-signal-a", type: "netTerminal", ref: "PORT1", value: "SENSOR_OUT", x: 560, y: 80, rotation: 0 },
    { id: "terminal-signal-b", type: "netTerminal", ref: "PORT2", value: "sensor out", x: 560, y: 150, rotation: 0 },
    { id: "terminal-power", type: "netTerminal", ref: "PORT3", value: "3V3", x: 560, y: 220, rotation: 0 }
  );
  payload.wires.push({
    id: "wire-power-port",
    from: { componentId: "component-21", pin: "VCC" },
    to: { componentId: "terminal-power", pin: "NET" },
    signal: "3V3",
    route: [{ x: 162, y: 78 }, { x: 162, y: 241 }, { x: 560, y: 241 }]
  });
  assert.equal(api.importCircuit(payload).ok, true);

  const componentPackage = api.exportComponentPackage({
    name: "Sensor Front End",
    prefix: "AFE",
    version: "1.2.0",
    description: "Reusable sensor conditioning circuit"
  });
  assert.equal(componentPackage.kind, "AliceSIMComponent");
  assert.equal(componentPackage.schemaVersion, 1);
  assert.equal(componentPackage.component.id, "sensor-front-end");
  assert.equal(componentPackage.component.prefix, "AFE");
  assert.equal(componentPackage.component.version, "1.2.0");
  assert.equal(componentPackage.component.componentCount, api.exportCircuit().components.length);
  assert.deepEqual(JSON.parse(JSON.stringify(componentPackage.component.ports.map((port) => port.name))), ["3V3", "SENSOR_OUT"]);
  const powerPort = componentPackage.component.ports.find((port) => port.name === "3V3");
  const signalPort = componentPackage.component.ports.find((port) => port.name === "SENSOR_OUT");
  assert.equal(powerPort.role, "power");
  assert.equal(powerPort.direction, "output");
  assert.deepEqual(JSON.parse(JSON.stringify(signalPort.terminalIds)), ["terminal-signal-a", "terminal-signal-b"]);

  const serialized = api.serializeComponentPackage(componentPackage);
  const inspected = api.inspectComponentPackage(serialized);
  assert.equal(inspected.ok, true, inspected.error);
  assert.equal(inspected.component.name, "Sensor Front End");
  assert.equal(inspected.circuit.kind, "AliceSIMCircuit");

  const downloaded = api.downloadComponentPackage("sensor-front-end", { name: "Sensor Front End", prefix: "AFE", version: "1.2.0" });
  assert.equal(downloaded.ok, false);
  assert.equal(downloaded.filename, "sensor-front-end.alice-component.json");
  assert.equal(JSON.parse(downloaded.content).kind, "AliceSIMComponent");
});

test("component package validation rejects mismatched external terminal contracts", () => {
  const api = loadSchematicApi();
  const payload = sampleCircuit();
  payload.components.push({ id: "terminal-a", type: "netTerminal", ref: "PORT1", value: "INPUT", x: 560, y: 80, rotation: 0 });
  assert.equal(api.importCircuit(payload).ok, true);
  const componentPackage = JSON.parse(JSON.stringify(api.exportComponentPackage({ name: "Input Module", prefix: "INM", version: "1.0.0" })));
  componentPackage.component.ports[0].terminalIds[0] = "missing-terminal";
  const inspected = api.inspectComponentPackage(componentPackage);
  assert.equal(inspected.ok, false);
  assert.equal(inspected.code, "UNKNOWN_COMPONENT_TERMINAL");
});

test("potentiometer drives ADC voltage and MOSFET switches drain to source", () => {
  const api = loadSchematicApi();
  api.setMcuConfiguration({
    mcu: "STM32F103C8T6",
    configuredPins: [
      { base: "PA0", signal: "ADC1_IN0", mode: "analog" },
      { base: "PB0", signal: "GPIO_Output", mode: "output" },
      { base: "PB1", signal: "GPIO_Input", mode: "input" }
    ]
  });
  const result = api.importCircuit({
    schemaVersion: 1,
    kind: "AliceSIMCircuit",
    mcu: "STM32F103C8T6",
    components: [
      { id: "mcu", type: "mcu", ref: "U1", value: "STM32F103C8T6", x: 80, y: 120, rotation: 0 },
      { id: "vcc", type: "vcc", ref: "PWR1", value: "+3V3", x: 360, y: 40, rotation: 0 },
      { id: "gnd", type: "ground", ref: "GND1", value: "0V", x: 360, y: 360, rotation: 0 },
      { id: "pot", type: "potentiometer", ref: "RV1", value: "50.0 %", x: 480, y: 100, rotation: 0, peripheralProperties: { percent: 50 } },
      { id: "mos", type: "mosfet", ref: "Q1", value: "N-MOS · VTH 2.0 V", x: 480, y: 260, rotation: 0, peripheralProperties: { gateThresholdV: 2, rdsOnMilliohm: 35 } }
    ],
    wires: [
      { id: "w1", from: { componentId: "vcc", pin: "VCC" }, to: { componentId: "pot", pin: "VCC" }, route: [{ x: 390, y: 100 }, { x: 480, y: 100 }] },
      { id: "w2", from: { componentId: "gnd", pin: "GND" }, to: { componentId: "pot", pin: "GND" }, route: [{ x: 390, y: 360 }, { x: 480, y: 360 }] },
      { id: "w3", from: { componentId: "pot", pin: "AO" }, to: { componentId: "mcu", pin: "PA0" }, route: [{ x: 250, y: 150 }, { x: 596, y: 150 }] },
      { id: "w4", from: { componentId: "mcu", pin: "PB0" }, to: { componentId: "mos", pin: "G" }, route: [{ x: 250, y: 170 }, { x: 480, y: 170 }] },
      { id: "w5", from: { componentId: "gnd", pin: "GND" }, to: { componentId: "mos", pin: "S" }, route: [{ x: 390, y: 360 }, { x: 596, y: 360 }] },
      { id: "w6", from: { componentId: "mos", pin: "D" }, to: { componentId: "mcu", pin: "PB1" }, route: [{ x: 250, y: 190 }, { x: 596, y: 190 }] }
    ],
    view: { zoom: 1, panX: 0, panY: 0 }
  });
  assert.equal(result.ok, true, JSON.stringify(result));
  assert.equal(api.sampleAnalogMcuPin("PA0"), 1.65);
  api.driveMcuPin("PB0", 0);
  assert.equal(api.sampleMcuPin("PB1"), null);
  api.driveMcuPin("PB0", 1);
  assert.equal(api.sampleMcuPin("PB1"), 0);
  assert.equal(api.getState().components.find((component) => component.type === "mosfet").mosfetOn, true);
});

test("ADC acquisition source drives the real analog net, persists and supports envelopes", () => {
  const api = loadSchematicApi();
  api.applyProjectModel({
    mcu: "STM32F103C8T6",
    pins: { PA0: { physicalPin: "PA0", iocSignal: "ADC1_IN0", mode: "analog", configured: true } },
    adcs: { hadc1: { handle: "hadc1", instance: "ADC1", channels: [{ channel: "ADC_CHANNEL_0", pin: "PA0", rank: 1 }] } },
    outputs: {}
  });
  const result = api.importCircuit({
    schemaVersion: 1,
    kind: "AliceSIMCircuit",
    mcu: "STM32F103C8T6",
    components: [
      { id: "mcu", type: "mcu", ref: "U1", value: "STM32F103C8T6", x: 80, y: 120, rotation: 0 },
      { id: "adc-src", type: "adcSource", ref: "ADC1", value: "1.250 V", x: 420, y: 120, rotation: 0, adcVoltage: 1.25, adcReferenceVoltage: 3.3, adcBits: 12 }
    ],
    wires: [
      { id: "w1", from: { componentId: "adc-src", pin: "AO" }, to: { componentId: "mcu", pin: "PA0" }, route: [{ x: 250, y: 150 }, { x: 532, y: 150 }] }
    ],
    view: { zoom: 1, panX: 0, panY: 0 }
  });
  assert.equal(result.ok, true, JSON.stringify(result));
  assert.equal(api.sampleAnalogMcuPin("PA0"), 1.25);
  assert.ok(api.getAutomationTargets().some((target) => target.id === "adc-src:voltage" && target.max === 3.3 && target.unit === "V"));
  assert.equal(api.applyAutomationValue("adc-src:voltage", 2.75), 2.75);
  assert.equal(api.sampleAdc("ADC1", { pin: "PA0" }).raw, 3413);
  const saved = api.exportCircuit().components.find((component) => component.id === "adc-src");
  assert.equal(saved.adcVoltage, 2.75);
  assert.equal(saved.adcReferenceVoltage, 3.3);
  assert.equal(saved.adcBits, 12);
});

test("firmware model application never adds output components to a user circuit", () => {
  const api = loadSchematicApi();
  api.setMcuConfiguration({
    mcu: "STM32F103C8T6",
    configuredPins: [{ base: "PC13", signal: "GPIO_Output", mode: "output" }]
  });
  const loaded = api.importCircuit({
    schemaVersion: 1,
    kind: "AliceSIMCircuit",
    mcu: "STM32F103C8T6",
    components: [
      { id: "mcu", type: "mcu", ref: "U1", value: "STM32F103C8T6", x: 80, y: 120, rotation: 0 },
      { id: "user-resistor", type: "resistor", ref: "R1", value: "1 kOhm", x: 360, y: 120, rotation: 0 },
      { id: "user-led", type: "led", ref: "D1", value: "GREEN LED", x: 520, y: 114, rotation: 0 },
      { id: "user-ground", type: "ground", ref: "GND1", value: "0V", x: 650, y: 150, rotation: 0 }
    ],
    wires: [
      { id: "w1", from: { componentId: "mcu", pin: "PC13" }, to: { componentId: "user-resistor", pin: "1" }, route: [{ x: 250, y: 150 }, { x: 360, y: 150 }] },
      { id: "w2", from: { componentId: "user-resistor", pin: "2" }, to: { componentId: "user-led", pin: "A" }, route: [{ x: 456, y: 146 }, { x: 520, y: 146 }] },
      { id: "w3", from: { componentId: "user-led", pin: "K" }, to: { componentId: "user-ground", pin: "GND" }, route: [{ x: 592, y: 146 }, { x: 682, y: 146 }, { x: 682, y: 150 }] }
    ],
    view: { zoom: 1.25, panX: -30, panY: 20, userView: true }
  });
  assert.equal(loaded.ok, true, JSON.stringify(loaded));

  const before = api.exportCircuit();
  const result = api.applyProjectModel({
    mcu: "STM32F103C8T6",
    pins: { PC13: { physicalPin: "PC13", iocSignal: "GPIO_Output", mode: "output", configured: true } },
    outputs: { PC13: { pin: "PC13", label: "STATUS_LED", initial: 0 } }
  });
  const after = api.exportCircuit();

  assert.equal(result.generated.length, 0);
  assert.deepEqual(after.components.map(component => component.id), before.components.map(component => component.id));
  assert.deepEqual(
    after.wires.map(wire => ({ id: wire.id, from: wire.from, to: wire.to })),
    before.wires.map(wire => ({ id: wire.id, from: wire.from, to: wire.to }))
  );
  assert.deepEqual(after.view, before.view);
  assert.equal(after.components.filter(component => component.type === "resistor").length, 1);
  assert.equal(after.components.filter(component => component.type === "led").length, 1);
  assert.equal(after.components.filter(component => component.type === "ground").length, 1);
});

test("the STM32F103 HAL example circuit powers and connects its OLED and ADC source", () => {
  const api = loadSchematicApi();
  api.applyProjectModel({
    mcu: "STM32F103C8T6",
    pins: {
      PA0: { physicalPin: "PA0", iocSignal: "ADC1_IN0", mode: "analog", configured: true },
      PB0: { physicalPin: "PB0", iocSignal: "ADC2_IN8", mode: "analog", configured: true },
      PA1: { physicalPin: "PA1", iocSignal: "GPIO_Input", mode: "input", configured: true, label: "RUN_SWITCH" },
      PB6: { physicalPin: "PB6", iocSignal: "I2C1_SCL", mode: "I2C", configured: true },
      PB7: { physicalPin: "PB7", iocSignal: "I2C1_SDA", mode: "I2C", configured: true },
      PB12: { physicalPin: "PB12", iocSignal: "GPIO_Output", mode: "output", configured: true, label: "STATUS_LED" }
    },
    i2cs: { hi2c1: { handle: "hi2c1", instance: "I2C1", sclPin: "PB6", sdaPin: "PB7", clockSpeed: 100000 } },
    adcs: {
      hadc1: { handle: "hadc1", instance: "ADC1", channels: [{ channel: "ADC_CHANNEL_0", channelNumber: 0, pin: "PA0", rank: 1, slot: 1 }] },
      hadc2: { handle: "hadc2", instance: "ADC2", channels: [{ channel: "ADC_CHANNEL_8", channelNumber: 8, pin: "PB0", rank: 1, slot: 1 }] }
    },
    outputs: { PB12: { pin: "PB12", label: "STATUS_LED", initial: 0 } }
  });
  const circuitPath = path.join(__dirname, "..", "examples", "STM32F103_HAL_Init", "STM32F103_HAL_Init.alice-sch.json");
  const circuitSource = fs.readFileSync(circuitPath, "utf8");
  const circuit = JSON.parse(circuitSource);
  const adcSource1 = circuit.components.find((component) => component.id === "adc-source-1");
  const adcSource2 = circuit.components.find((component) => component.id === "adc-source-2");
  const result = api.importCircuit(circuitSource);

  assert.equal(result.ok, true, JSON.stringify(result));
  assert.equal(result.skippedWireCount, 0);
  const oledTx = api.handleI2cTransmission({
    handle: "hi2c1",
    instance: "I2C1",
    deviceAddress: 0x78,
    memoryAddress: 0,
    buffer: [0xae],
    length: 1
  });
  assert.equal(oledTx.accepted, true);
  assert.equal(oledTx.targetCount, 1);
  const firmwareInputs = api.getFirmwareInputSnapshot();
  assert.equal(firmwareInputs.i2c.length, 1);
  assert.equal(firmwareInputs.i2c[0].componentId, "oled-1");
  assert.equal(firmwareInputs.i2c[0].instance, "I2C1");
  assert.equal(firmwareInputs.i2c[0].handle, "hi2c1");
  assert.equal(firmwareInputs.i2c[0].address, 0x3c);
  assert.equal(firmwareInputs.i2c[0].ready, true);
  const oled = api.getState().components.find((component) => component.id === "oled-1");
  assert.deepEqual(JSON.parse(JSON.stringify(oled.deviceState.connection)), {
    powered: true,
    busConnected: true,
    bindingValid: true,
    vccLevel: 3.3,
    gndLevel: 0,
    sclPin: "PB6",
    sdaPin: "PB7",
    reason: ""
  });
  const adc1 = api.sampleAdc("hadc1");
  assert.equal(adc1.connected, true);
  assert.equal(adc1.voltage, adcSource1.adcVoltage);
  assert.equal(adc1.raw, Math.round(adcSource1.adcVoltage / adcSource1.adcReferenceVoltage * 4095));
  assert.equal(adc1.pin, "PA0");
  const adc2 = api.sampleAdc("hadc2");
  assert.equal(adc2.connected, true);
  assert.equal(adc2.voltage, adcSource2.adcVoltage);
  assert.equal(adc2.raw, Math.round(adcSource2.adcVoltage / adcSource2.adcReferenceVoltage * 4095));
  assert.equal(adc2.pin, "PB0");
  assert.equal(api.sampleMcuPin("PA1"), 1);
  assert.equal(api.setButtonClosed("run-switch", true), true);
  assert.equal(api.sampleMcuPin("PA1"), 0);
  api.driveMcuPin("PB12", 1);
  let ledStates = api.compileNetlist().leds;
  assert.equal(ledStates.find((led) => led.componentId === "green-led").on, true);
  assert.equal(ledStates.find((led) => led.componentId === "red-led").on, false);
  api.driveMcuPin("PB12", 0);
  ledStates = api.compileNetlist().leds;
  assert.equal(ledStates.find((led) => led.componentId === "green-led").on, false);
  assert.equal(ledStates.find((led) => led.componentId === "red-led").on, true);
});

test("the matching example circuit keeps MCU wires when it loads before the firmware pin model", () => {
  const api = loadSchematicApi();
  const circuitPath = path.join(__dirname, "..", "examples", "STM32F103_HAL_Init", "STM32F103_HAL_Init.alice-sch.json");
  const circuitSource = fs.readFileSync(circuitPath, "utf8");
  const circuit = JSON.parse(circuitSource);
  const adcSource1 = circuit.components.find((component) => component.id === "adc-source-1");
  const adcSource2 = circuit.components.find((component) => component.id === "adc-source-2");
  const result = api.importCircuit(circuitSource);

  assert.equal(result.ok, true, JSON.stringify(result));
  assert.equal(result.skippedWireCount, 0);
  assert.equal(api.exportCircuit().wires.length, 20);

  api.applyProjectModel({
    mcu: "STM32F103C8T6",
    pins: {
      PA0: { physicalPin: "PA0", iocSignal: "ADC1_IN0", mode: "analog", configured: true },
      PB0: { physicalPin: "PB0", iocSignal: "ADC2_IN8", mode: "analog", configured: true },
      PA1: { physicalPin: "PA1", iocSignal: "GPIO_Input", mode: "input", configured: true, label: "RUN_SWITCH" },
      PB6: { physicalPin: "PB6", iocSignal: "I2C1_SCL", mode: "I2C", configured: true },
      PB7: { physicalPin: "PB7", iocSignal: "I2C1_SDA", mode: "I2C", configured: true },
      PB12: { physicalPin: "PB12", iocSignal: "GPIO_Output", mode: "output", configured: true, label: "STATUS_LED" }
    },
    i2cs: { hi2c1: { handle: "hi2c1", instance: "I2C1", sclPin: "PB6", sdaPin: "PB7", clockSpeed: 100000 } },
    adcs: {
      hadc1: { handle: "hadc1", instance: "ADC1", channels: [{ channel: "ADC_CHANNEL_0", pin: "PA0", rank: 1 }] },
      hadc2: { handle: "hadc2", instance: "ADC2", channels: [{ channel: "ADC_CHANNEL_8", pin: "PB0", rank: 1 }] }
    },
    outputs: { PB12: { pin: "PB12", label: "STATUS_LED", initial: 0 } }
  });

  const adc1 = api.sampleAdc("hadc1", { pin: "PA0", channel: "ADC_CHANNEL_0" });
  assert.equal(adc1.connected, true);
  assert.equal(adc1.voltage, adcSource1.adcVoltage);
  assert.equal(adc1.raw, Math.round(adcSource1.adcVoltage / adcSource1.adcReferenceVoltage * 4095));
  const adc2 = api.sampleAdc("hadc2", { pin: "PB0", channel: "ADC_CHANNEL_8" });
  assert.equal(adc2.connected, true);
  assert.equal(adc2.voltage, adcSource2.adcVoltage);
  assert.equal(adc2.raw, Math.round(adcSource2.adcVoltage / adcSource2.adcReferenceVoltage * 4095));
  assert.equal(api.handleI2cTransmission({
    handle: "hi2c1",
    instance: "I2C1",
    deviceAddress: 0x78,
    memoryAddress: 0,
    buffer: [0xaf],
    length: 1
  }).accepted, true);
});

test("conditional UART sender waits on the unified timestamp and feeds the wired UART RX", () => {
  const queued = [];
  const api = loadSchematicApi({ halSimulator: { enqueueSerial(text, instance) { queued.push({ text, instance }); return { timeMs: 10 }; } } });
  api.applyProjectModel({
    mcu: "STM32F103C8T6",
    pins: { PA3: { physicalPin: "PA3", iocSignal: "USART2_RX", mode: "communication", configured: true } },
    uarts: { huart2: { handle: "huart2", instance: "USART2", rxPin: "PA3", txPin: "PA2", receiveCalls: [{ operationId: "rx-1" }] } },
    outputs: {}
  });
  const result = api.importCircuit({
    schemaVersion: 1,
    kind: "AliceSIMCircuit",
    mcu: "STM32F103C8T6",
    components: [
      { id: "mcu", type: "mcu", ref: "U1", value: "STM32F103C8T6", x: 80, y: 120, rotation: 0 },
      { id: "sender", type: "uartSender", ref: "TXG1", value: "启动后 · 10 ms", x: 420, y: 120, rotation: 0, uartPayload: "OK\\r\\n", uartCondition: "startup", uartDelayMs: 10 }
    ],
    wires: [
      { id: "w1", from: { componentId: "sender", pin: "TX" }, to: { componentId: "mcu", pin: "PA3" }, route: [{ x: 250, y: 150 }, { x: 546, y: 150 }] }
    ],
    view: { zoom: 1, panX: 0, panY: 0 }
  });
  assert.equal(result.ok, true, JSON.stringify(result));
  api.tick(9, 1);
  assert.equal(queued.length, 0);
  api.tick(10, 2);
  assert.deepEqual(queued, [{ text: "OK\r\n", instance: "USART2" }]);
  api.tick(100, 3);
  assert.equal(queued.length, 1, "startup mode sends only once");
  const saved = api.exportCircuit().components.find((component) => component.id === "sender");
  assert.equal(saved.uartPayload, "OK\\r\\n");
  assert.equal(saved.uartCondition, "startup");
  assert.equal(saved.uartDelayMs, 10);
});

test("LED networks retain the duty cycle of a connected MCU PWM channel", () => {
  const api = loadSchematicApi();
  api.applyProjectModel({
    mcu: "STM32F103C8T6",
    pins: { PA0: { physicalPin: "PA0", iocSignal: "TIM2_CH1", configured: true } },
    timers: { htim2: { handle: "htim2", instance: "TIM2", period: 999, frequencyHz: 1000, channels: [{ channelNumber: 1, pin: "PA0" }] } },
    outputs: {},
    program: { operations: [] }
  });
  const loaded = api.importCircuit({
    schemaVersion: 1,
    kind: "AliceSIMCircuit",
    mcu: "STM32F103C8T6",
    components: [
      { id: "mcu", type: "mcu", ref: "U1", value: "STM32F103C8T6", x: 50, y: 80, rotation: 0 },
      { id: "r1", type: "resistor", ref: "R1", value: "220 Ohm", x: 250, y: 100, rotation: 0 },
      { id: "led1", type: "led", ref: "LED1", value: "RED", x: 360, y: 100, rotation: 0 },
      { id: "gnd", type: "ground", ref: "GND1", value: "0V", x: 470, y: 160, rotation: 0 }
    ],
    wires: [
      { id: "w1", from: { componentId: "mcu", pin: "PA0" }, to: { componentId: "r1", pin: "1" }, signal: "TIM2_CH1", route: [{ x: 100, y: 100 }, { x: 250, y: 100 }] },
      { id: "w2", from: { componentId: "r1", pin: "2" }, to: { componentId: "led1", pin: "A" }, signal: "PWM_LED", route: [{ x: 300, y: 100 }, { x: 360, y: 100 }] },
      { id: "w3", from: { componentId: "led1", pin: "K" }, to: { componentId: "gnd", pin: "GND" }, signal: "GND", route: [{ x: 420, y: 100 }, { x: 470, y: 100 }, { x: 470, y: 160 }] }
    ]
  });
  assert.equal(loaded.ok, true, loaded.error);

  const result = api.driveMcuPwm({ instance: "TIM2", channel: 1, pin: "PA0", active: true, compare: 375, period: 999, dutyCycle: 0.375, frequencyHz: 1000 });
  assert.equal(result.dutyPercent, 37.5);
  const led = api.compileNetlist().leds.find(item => item.componentId === "led1");
  assert.equal(led.pwm.dutyPercent, 37.5);
  assert.equal(led.pwm.frequencyHz, 1000);
  assert.equal(api.getState().mcuPwm.PA0.dutyCycle, 0.375);
});

test("wired SPI display receives HAL transfers using CS and DC GPIO levels", () => {
  const api = loadSchematicApi();
  api.applyProjectModel({
    mcu: "STM32F103C8T6",
    pins: {
      PA5: { physicalPin: "PA5", iocSignal: "SPI1_SCK", mode: "communication", configured: true },
      PA7: { physicalPin: "PA7", iocSignal: "SPI1_MOSI", mode: "communication", configured: true },
      PB0: { physicalPin: "PB0", iocSignal: "GPIO_Output", mode: "output", configured: true },
      PB1: { physicalPin: "PB1", iocSignal: "GPIO_Output", mode: "output", configured: true }
    },
    spis: { hspi1: { handle: "hspi1", instance: "SPI1", sckPin: "PA5", mosiPin: "PA7", transmitCalls: [{ operationId: "spi-1" }] } },
    outputs: {}
  });
  const result = api.importCircuit({
    schemaVersion: 1,
    kind: "AliceSIMCircuit",
    mcu: "STM32F103C8T6",
    components: [
      { id: "mcu", type: "mcu", ref: "U1", value: "STM32F103C8T6", x: 80, y: 120, rotation: 0 },
      { id: "vcc", type: "vcc", ref: "PWR1", value: "+3V3", x: 360, y: 30, rotation: 0 },
      { id: "gnd", type: "ground", ref: "GND1", value: "0V", x: 360, y: 400, rotation: 0 },
      { id: "tft", type: "spiDisplay", ref: "TFT1", value: "ST7735 · 160×128", x: 500, y: 130, rotation: 0 }
    ],
    wires: [
      { id: "w1", from: { componentId: "vcc", pin: "VCC" }, to: { componentId: "tft", pin: "VCC" }, route: [{ x: 392, y: 100 }, { x: 500, y: 100 }] },
      { id: "w2", from: { componentId: "gnd", pin: "GND" }, to: { componentId: "tft", pin: "GND" }, route: [{ x: 392, y: 400 }, { x: 500, y: 400 }] },
      { id: "w3", from: { componentId: "mcu", pin: "PA5" }, to: { componentId: "tft", pin: "SCK" }, route: [{ x: 250, y: 150 }, { x: 644, y: 150 }] },
      { id: "w4", from: { componentId: "mcu", pin: "PA7" }, to: { componentId: "tft", pin: "MOSI" }, route: [{ x: 250, y: 170 }, { x: 644, y: 170 }] },
      { id: "w5", from: { componentId: "mcu", pin: "PB0" }, to: { componentId: "tft", pin: "CS" }, route: [{ x: 250, y: 190 }, { x: 644, y: 190 }] },
      { id: "w6", from: { componentId: "mcu", pin: "PB1" }, to: { componentId: "tft", pin: "DC" }, route: [{ x: 250, y: 210 }, { x: 500, y: 210 }] }
    ],
    view: { zoom: 1, panX: 0, panY: 0 }
  });
  assert.equal(result.ok, true, JSON.stringify(result));
  api.driveMcuPin("PB0", 0);
  api.driveMcuPin("PB1", 0);
  const firmwareInputs = api.getFirmwareInputSnapshot();
  assert.equal(firmwareInputs.spi.length, 1);
  assert.equal(firmwareInputs.spi[0].componentId, "tft");
  assert.equal(firmwareInputs.spi[0].instance, "SPI1");
  assert.equal(firmwareInputs.spi[0].handle, "hspi1");
  assert.equal(firmwareInputs.spi[0].csPin, "PB0");
  assert.equal(firmwareInputs.spi[0].dcPin, "PB1");
  assert.equal(firmwareInputs.spi[0].selected, true);
  assert.equal(firmwareInputs.spi[0].dataMode, false);
  assert.equal(firmwareInputs.spi[0].ready, true);
  assert.equal(api.handleSpiTransmission({ instance: "SPI1", bytes: [0x11] }).accepted, true);
  assert.equal(api.handleSpiTransmission({ instance: "SPI1", bytes: [0x29] }).accepted, true);
  api.driveMcuPin("PB1", 1);
  api.driveMcuPin("PB1", 0);
  api.handleSpiTransmission({ instance: "SPI1", bytes: [0x2c] });
  api.driveMcuPin("PB1", 1);
  assert.equal(api.handleSpiTransmission({ instance: "SPI1", bytes: [0xf8, 0x00] }).accepted, true);
  const display = api.getState().components.find((component) => component.id === "tft").deviceState;
  assert.equal(display.visible, true);
  assert.ok(display.bytesReceived >= 5);
});

test("sensor automation targets update real schematic input properties", () => {
  const api = loadSchematicApi();
  const payload = sampleCircuit();
  payload.components.push({
    id: "component-60",
    type: "potentiometer",
    ref: "RV2",
    value: "50.0 %",
    x: 560,
    y: 260,
    rotation: 0,
    peripheralProperties: { percent: 50 }
  });
  assert.equal(api.importCircuit(payload).ok, true);

  const targets = api.getAutomationTargets();
  assert.ok(targets.some((target) => target.id === "component-40:lux" && target.unit === "lux"));
  assert.ok(targets.some((target) => target.id === "component-60:percent" && target.unit === "%"));

  assert.equal(api.applyAutomationValue("component-40:lux", 75000), 75000);
  assert.equal(api.applyAutomationValue("component-60:percent", 82.5), 82.5);
  const state = api.getState();
  assert.equal(state.components.find((component) => component.id === "component-40").lux, 75000);
  assert.equal(state.components.find((component) => component.id === "component-60").peripheralProperties.percent, 82.5);
  assert.equal(api.applyAutomationValue("component-60:gateThresholdV", 4), false);
});

test("EDA network terminals merge equal labels without long wires", () => {
  const api = loadSchematicApi();
  const payload = sampleCircuit();
  payload.components.push(
    { id: "terminal-a", type: "netTerminal", ref: "PORT1", value: "SENSOR_BUS", x: 520, y: 80, rotation: 0 },
    { id: "terminal-b", type: "netTerminal", ref: "PORT2", value: "sensor bus", x: 520, y: 160, rotation: 180 },
    { id: "terminal-c", type: "netTerminal", ref: "PORT3", value: "OTHER_BUS", x: 520, y: 240, rotation: 90 }
  );
  assert.equal(api.importCircuit(payload).ok, true);

  let compiled = api.compileNetlist();
  const firstNet = compiled.endpointToNet["terminal-a:NET"];
  assert.equal(compiled.endpointToNet["terminal-b:NET"], firstNet);
  assert.notEqual(compiled.endpointToNet["terminal-c:NET"], firstNet);
  assert.deepEqual(JSON.parse(JSON.stringify(compiled.netById.get(firstNet).labels)), ["SENSOR_BUS"]);

  assert.equal(api.setComponentValue("terminal-b", "OTHER_BUS"), true);
  compiled = api.compileNetlist();
  assert.notEqual(compiled.endpointToNet["terminal-a:NET"], compiled.endpointToNet["terminal-b:NET"]);
  assert.equal(compiled.endpointToNet["terminal-b:NET"], compiled.endpointToNet["terminal-c:NET"]);

  const saved = api.exportCircuit();
  assert.equal(saved.components.find(component => component.id === "terminal-b").value, "OTHER_BUS");
});

test("voltage and current probes use real nets and survive circuit files", () => {
  const api = loadSchematicApi();
  const result = api.importCircuit({
    schemaVersion: 1,
    kind: "AliceSIMCircuit",
    mcu: "STM32F103C8T6",
    components: [
      { id: "supply", type: "vcc", ref: "PWR1", value: "+5V", x: 80, y: 40, rotation: 0 },
      { id: "current-supply", type: "vcc", ref: "PWR2", value: "+5V", x: 80, y: 150, rotation: 0 },
      { id: "ground", type: "ground", ref: "GND1", value: "0V", x: 80, y: 260, rotation: 0 },
      { id: "vp", type: "voltageProbe", ref: "VP1", value: "— V", x: 260, y: 60, rotation: 0 },
      { id: "ip", type: "currentProbe", ref: "IP1", value: "— A", x: 260, y: 220, rotation: 0 },
      { id: "load", type: "resistor", ref: "R1", value: "330 Ω", x: 420, y: 220, rotation: 0 },
      { id: "load-2", type: "resistor", ref: "R2", value: "660 Ω", x: 420, y: 300, rotation: 0 }
    ],
    wires: [
      { id: "probe-v", from: { componentId: "supply", pin: "VCC" }, to: { componentId: "vp", pin: "TIP" }, route: [{ x: 112, y: 98 }, { x: 260, y: 98 }] },
      { id: "probe-i-in", from: { componentId: "current-supply", pin: "VCC" }, to: { componentId: "ip", pin: "IN" }, route: [{ x: 112, y: 208 }, { x: 180, y: 208 }, { x: 180, y: 253 }, { x: 260, y: 253 }] },
      { id: "probe-i-load", from: { componentId: "ip", pin: "OUT" }, to: { componentId: "load", pin: "1" }, route: [{ x: 364, y: 253 }, { x: 420, y: 253 }] },
      { id: "probe-i-load-2", from: { componentId: "ip", pin: "OUT" }, to: { componentId: "load-2", pin: "1" }, route: [{ x: 364, y: 253 }, { x: 390, y: 253 }, { x: 390, y: 333 }, { x: 420, y: 333 }] },
      { id: "load-ground", from: { componentId: "load", pin: "2" }, to: { componentId: "ground", pin: "GND" }, route: [{ x: 516, y: 246 }, { x: 516, y: 260 }, { x: 112, y: 260 }] },
      { id: "load-2-ground", from: { componentId: "load-2", pin: "2" }, to: { componentId: "ground", pin: "GND" }, route: [{ x: 516, y: 326 }, { x: 540, y: 326 }, { x: 540, y: 260 }, { x: 112, y: 260 }] }
    ],
    view: { zoom: 1, panX: 0, panY: 0, userView: true }
  });
  assert.equal(result.ok, true, JSON.stringify(result));

  const voltage = api.sampleProbe("vp");
  assert.equal(voltage.code, "measured");
  assert.equal(voltage.value, 5);
  assert.equal(voltage.text, "5.000 V");

  const current = api.sampleProbe("ip");
  assert.equal(current.code, "measured");
  assert.equal(current.method, "resistive-mna");
  assert.ok(Math.abs(current.value - (5 / 330 + 5 / 660)) < 1e-9);
  assert.equal(current.text, "22.73 mA");
  const currentNet = api.compileNetlist().netById.get(api.compileNetlist().endpointToNet["ip:IN"]);
  assert.equal(currentNet.conflict, false);

  const saved = api.exportCircuit();
  assert.equal(saved.components.find(component => component.id === "vp").value, "— V");
  assert.equal(saved.components.find(component => component.id === "ip").value, "— A");
  assert.equal(api.importCircuit(JSON.stringify(saved)).ok, true);
  assert.equal(api.sampleProbe("vp").text, "5.000 V");
  assert.equal(api.sampleProbe("ip").text, "22.73 mA");

  assert.equal(api.setPowerCalculationEnabled(false), false);
  assert.equal(api.sampleProbe("vp").text, "5.000 V", "voltage probes stay active in voltage-only mode");
  assert.equal(api.sampleProbe("ip").code, "disabled");
  assert.equal(api.sampleProbe("ip").text, "— A");
  assert.equal(api.getPowerReport().mode, "voltage-only");
  assert.deepEqual(JSON.parse(JSON.stringify(api.getPowerReport().components)), []);
});

test("DC power report calculates resistor dissipation and raises overloads", () => {
  const api = loadSchematicApi();
  const result = api.importCircuit({
    schemaVersion: 1,
    kind: "AliceSIMCircuit",
    mcu: "STM32F103C8T6",
    components: [
      { id: "supply", type: "vcc", ref: "PWR1", value: "+3.3 V · 1 A", x: 80, y: 40, rotation: 0 },
      { id: "ground", type: "ground", ref: "GND1", value: "0V", x: 80, y: 260, rotation: 0 },
      { id: "load", type: "resistor", ref: "R1", value: "10 Ω · 0.25 W", x: 300, y: 120, rotation: 0 }
    ],
    wires: [
      { id: "w1", from: { componentId: "supply", pin: "VCC" }, to: { componentId: "load", pin: "1" }, route: [{ x: 112, y: 98 }, { x: 300, y: 98 }, { x: 300, y: 146 }] },
      { id: "w2", from: { componentId: "load", pin: "2" }, to: { componentId: "ground", pin: "GND" }, route: [{ x: 396, y: 146 }, { x: 396, y: 260 }, { x: 112, y: 260 }] }
    ],
    view: { zoom: 1, panX: 0, panY: 0 }
  });
  assert.equal(result.ok, true, JSON.stringify(result));
  const report = api.getPowerReport();
  const resistor = report.components.find((entry) => entry.componentId === "load");
  const supply = report.components.find((entry) => entry.componentId === "supply");
  assert.ok(Math.abs(resistor.currentA - 0.33) < 1e-9);
  assert.ok(Math.abs(resistor.powerW - 1.089) < 1e-9);
  assert.equal(resistor.overload, true);
  assert.equal(supply.overload, false);
  assert.deepEqual(JSON.parse(JSON.stringify(report.alerts.map((entry) => entry.ref))), ["R1"]);

  assert.equal(api.setComponentValue("load", "330 Ω · 0.25 W"), true);
  const safeReport = api.getPowerReport();
  const safeResistor = safeReport.components.find((entry) => entry.componentId === "load");
  assert.ok(Math.abs(safeResistor.currentA - 0.01) < 1e-9);
  assert.ok(Math.abs(safeResistor.powerW - 0.033) < 1e-9);
  assert.equal(safeResistor.overload, false);
  assert.equal(safeReport.overloadCount, 0);
});

test("MCU GPIO drives an LED through its resistor with real current and power", () => {
  const api = loadSchematicApi();
  const result = api.importCircuit({
    schemaVersion: 1,
    kind: "AliceSIMCircuit",
    mcu: "STM32F103C8T6",
    components: [
      { id: "mcu", type: "mcu", ref: "U1", value: "STM32F103C8T6", x: 60, y: 80, rotation: 0, autoGenerated: true, autoSource: "system", autoKey: "mcu" },
      { id: "resistor", type: "resistor", ref: "R1", value: "330 Ω · 0.25 W", x: 300, y: 80, rotation: 0 },
      { id: "led", type: "led", ref: "D1", value: "RED LED · 20 mA", x: 470, y: 74, rotation: 0 },
      { id: "ground", type: "ground", ref: "GND1", value: "0V", x: 620, y: 100, rotation: 0 }
    ],
    wires: [
      { id: "w1", from: { componentId: "mcu", pin: "PC13" }, to: { componentId: "resistor", pin: "1" }, route: [{ x: 230, y: 110 }, { x: 300, y: 110 }, { x: 300, y: 106 }] },
      { id: "w2", from: { componentId: "resistor", pin: "2" }, to: { componentId: "led", pin: "A" }, route: [{ x: 396, y: 106 }, { x: 470, y: 106 }] },
      { id: "w3", from: { componentId: "led", pin: "K" }, to: { componentId: "ground", pin: "GND" }, route: [{ x: 542, y: 106 }, { x: 652, y: 106 }, { x: 652, y: 100 }] }
    ],
    view: { zoom: 1, panX: 0, panY: 0 }
  });
  assert.equal(result.ok, true, JSON.stringify(result));

  assert.equal(api.driveMcuPin("PC13", 1), 1);
  let netlist = api.compileNetlist();
  let report = api.getPowerReport();
  const led = report.components.find((entry) => entry.componentId === "led");
  const resistor = report.components.find((entry) => entry.componentId === "resistor");
  const mcu = report.components.find((entry) => entry.componentId === "mcu");

  assert.equal(netlist.leds.find((entry) => entry.componentId === "led").on, true);
  assert.ok(led.currentA > 0.004 && led.currentA < 0.005);
  assert.ok(led.powerW > 0.007);
  assert.ok(Math.abs(resistor.currentA - led.currentA) < 1e-9);
  assert.ok(Math.abs(mcu.currentA - led.currentA) < 1e-9);
  assert.equal(led.overload, false);

  assert.equal(api.driveMcuPin("PC13", 0), 0);
  netlist = api.compileNetlist();
  report = api.getPowerReport();
  assert.equal(netlist.leds.find((entry) => entry.componentId === "led").on, false);
  assert.equal(report.components.find((entry) => entry.componentId === "led").powerW, 0);

  assert.equal(api.setPowerCalculationEnabled(false), false);
  assert.equal(api.driveMcuPin("PC13", 1), 1);
  netlist = api.compileNetlist();
  report = api.getPowerReport();
  assert.equal(netlist.leds.find((entry) => entry.componentId === "led").on, true, "voltage still controls LED state");
  assert.equal(report.enabled, false);
  assert.equal(report.mode, "voltage-only");
  assert.equal(report.components.length, 0);
  assert.equal(report.alerts.length, 0);
});

test("DC-DC converter reports efficiency, upstream input power and output overload", () => {
  const api = loadSchematicApi();
  const result = api.importCircuit({
    schemaVersion: 1,
    kind: "AliceSIMCircuit",
    mcu: "STM32F103C8T6",
    components: [
      { id: "supply", type: "vcc", ref: "PWR1", value: "+12 V · 1 A", x: 80, y: 40, rotation: 0 },
      { id: "ground", type: "ground", ref: "GND1", value: "0V", x: 80, y: 300, rotation: 0 },
      { id: "converter", type: "dcDcConverter", ref: "PSU1", value: "5.0 V · 0.25 A · 90%", x: 280, y: 100, rotation: 0, peripheralProperties: { outputVoltageV: 5, maxOutputCurrentA: 0.25, efficiencyPercent: 90, quiescentCurrentMa: 5, enabled: 1 } },
      { id: "load", type: "resistor", ref: "R1", value: "10 Ω · 5 W", x: 520, y: 140, rotation: 0 }
    ],
    wires: [
      { id: "w1", from: { componentId: "supply", pin: "VCC" }, to: { componentId: "converter", pin: "VIN" }, route: [{ x: 112, y: 98 }, { x: 280, y: 98 }, { x: 280, y: 116 }] },
      { id: "w2", from: { componentId: "converter", pin: "GND" }, to: { componentId: "ground", pin: "GND" }, route: [{ x: 280, y: 144 }, { x: 280, y: 300 }, { x: 112, y: 300 }] },
      { id: "w3", from: { componentId: "converter", pin: "VOUT" }, to: { componentId: "load", pin: "1" }, route: [{ x: 396, y: 144 }, { x: 520, y: 144 }, { x: 520, y: 166 }] },
      { id: "w4", from: { componentId: "load", pin: "2" }, to: { componentId: "ground", pin: "GND" }, route: [{ x: 616, y: 166 }, { x: 616, y: 300 }, { x: 112, y: 300 }] }
    ],
    view: { zoom: 1, panX: 0, panY: 0 }
  });
  assert.equal(result.ok, true, JSON.stringify(result));
  const report = api.getPowerReport();
  const converter = report.components.find((entry) => entry.componentId === "converter");
  const supply = report.components.find((entry) => entry.componentId === "supply");
  assert.ok(Math.abs(converter.outputVoltageV - 5) < 1e-9);
  assert.ok(Math.abs(converter.outputCurrentA - 0.5) < 1e-9);
  assert.ok(Math.abs(converter.outputPowerW - 2.5) < 1e-9);
  assert.ok(Math.abs(converter.inputPowerW - (2.5 / 0.9 + 12 * 0.005)) < 1e-9);
  assert.ok(Math.abs(supply.currentA - converter.inputCurrentA) < 1e-9);
  assert.equal(converter.overload, true);
  assert.ok(report.alerts.some((entry) => entry.ref === "PSU1"));

  const saved = api.exportCircuit();
  assert.deepEqual(JSON.parse(JSON.stringify(saved.components.find((entry) => entry.id === "converter").peripheralProperties)), {
    outputVoltageV: 5,
    maxOutputCurrentA: 0.25,
    efficiencyPercent: 90,
    quiescentCurrentMa: 5,
    enabled: 1
  });
});
